export enum WizardEvent {
  Start = 'wizard.start',
  DocumentUploaded = 'wizard.documentUploaded',
  DocumentError = 'wizard.documentError',
  AuthCompleted = 'wizard.authCompleted',
  SpreadsheetLink = 'wizard.spreadsheetLink',
  SpreadsheetError = 'wizard.spreadsheetError',
  SupplyProcessing = 'wizard.supplyProcessing',
  TaskExpired = 'wizard.taskExpired',
  TaskCancelled = 'wizard.taskCancelled',
  OrderCancelFailed = 'wizard.orderCancelFailed',
  OrderCancelled = 'wizard.orderCancelled',
  SupplyError = 'wizard.supplyError',
  SupplyDone = 'wizard.supplyDone',
  ClusterSelected = 'wizard.clusterSelected',
  DropOffSelected = 'wizard.dropOffSelected',
  WarehouseSelected = 'wizard.warehouseSelected',
  TimeslotSelected = 'wizard.timeslotSelected',
  CallbackExpired = 'wizard.callbackExpired',
  DraftError = 'wizard.draftError',
  DraftCreated = 'wizard.draftCreated',
  DraftValid = 'wizard.draftValid',
  DraftExpired = 'wizard.draftExpired',
  DraftInvalid = 'wizard.draftInvalid',
  TimeslotMissing = 'wizard.timeslotMissing',
  WarehousePending = 'wizard.warehousePending',
  WindowExpired = 'wizard.windowExpired',
  SupplyCreated = 'wizard.supplyCreated',
  SupplyStatus = 'wizard.supplyStatus',
  NoCredentials = 'wizard.noCredentials',
  Error = 'wizard.error',
  TaskSummary = 'tasks.summary',
  TaskResumeFailed = 'task.resumeFailed',
  TaskResumedSupplyCreated = 'task.resumedSupplyCreated',
  TaskOrderIdRecovered = 'task.orderIdRecovered',
  AuthSaved = 'auth.saved',
  AuthCleared = 'auth.cleared',
}

export type WizardEventPayload = {
  lines?: Array<string | undefined>;
};
